// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreCustomSlotSupplierCallbacks {
 *     TemporalCoreCustomSlotSupplierReserveCallback reserve;
 *     TemporalCoreCustomSlotSupplierCancelReserveCallback cancel_reserve;
 *     TemporalCoreCustomSlotSupplierTryReserveCallback try_reserve;
 *     TemporalCoreCustomSlotSupplierMarkUsedCallback mark_used;
 *     TemporalCoreCustomSlotSupplierReleaseCallback release;
 *     TemporalCoreCustomSlotSupplierAvailableSlotsCallback available_slots;
 *     TemporalCoreCustomSlotSupplierFreeCallback free;
 *     void *user_data;
 * }
 * }
 */
public class TemporalCoreCustomSlotSupplierCallbacksStruct {

    TemporalCoreCustomSlotSupplierCallbacksStruct() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("reserve"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("cancel_reserve"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("try_reserve"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("mark_used"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("release"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("available_slots"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("free"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("user_data")
    ).withName("TemporalCoreCustomSlotSupplierCallbacks");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout reserve$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("reserve"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierReserveCallback reserve
     * }
     */
    public static final AddressLayout reserve$layout() {
        return reserve$LAYOUT;
    }

    private static final long reserve$OFFSET = $LAYOUT.byteOffset(groupElement("reserve"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierReserveCallback reserve
     * }
     */
    public static final long reserve$offset() {
        return reserve$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierReserveCallback reserve
     * }
     */
    public static MemorySegment reserve(MemorySegment struct) {
        return struct.get(reserve$LAYOUT, reserve$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierReserveCallback reserve
     * }
     */
    public static void reserve(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(reserve$LAYOUT, reserve$OFFSET, fieldValue);
    }

    private static final AddressLayout cancel_reserve$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cancel_reserve"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierCancelReserveCallback cancel_reserve
     * }
     */
    public static final AddressLayout cancel_reserve$layout() {
        return cancel_reserve$LAYOUT;
    }

    private static final long cancel_reserve$OFFSET = $LAYOUT.byteOffset(groupElement("cancel_reserve"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierCancelReserveCallback cancel_reserve
     * }
     */
    public static final long cancel_reserve$offset() {
        return cancel_reserve$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierCancelReserveCallback cancel_reserve
     * }
     */
    public static MemorySegment cancel_reserve(MemorySegment struct) {
        return struct.get(cancel_reserve$LAYOUT, cancel_reserve$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierCancelReserveCallback cancel_reserve
     * }
     */
    public static void cancel_reserve(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cancel_reserve$LAYOUT, cancel_reserve$OFFSET, fieldValue);
    }

    private static final AddressLayout try_reserve$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("try_reserve"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierTryReserveCallback try_reserve
     * }
     */
    public static final AddressLayout try_reserve$layout() {
        return try_reserve$LAYOUT;
    }

    private static final long try_reserve$OFFSET = $LAYOUT.byteOffset(groupElement("try_reserve"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierTryReserveCallback try_reserve
     * }
     */
    public static final long try_reserve$offset() {
        return try_reserve$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierTryReserveCallback try_reserve
     * }
     */
    public static MemorySegment try_reserve(MemorySegment struct) {
        return struct.get(try_reserve$LAYOUT, try_reserve$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierTryReserveCallback try_reserve
     * }
     */
    public static void try_reserve(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(try_reserve$LAYOUT, try_reserve$OFFSET, fieldValue);
    }

    private static final AddressLayout mark_used$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("mark_used"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierMarkUsedCallback mark_used
     * }
     */
    public static final AddressLayout mark_used$layout() {
        return mark_used$LAYOUT;
    }

    private static final long mark_used$OFFSET = $LAYOUT.byteOffset(groupElement("mark_used"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierMarkUsedCallback mark_used
     * }
     */
    public static final long mark_used$offset() {
        return mark_used$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierMarkUsedCallback mark_used
     * }
     */
    public static MemorySegment mark_used(MemorySegment struct) {
        return struct.get(mark_used$LAYOUT, mark_used$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierMarkUsedCallback mark_used
     * }
     */
    public static void mark_used(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(mark_used$LAYOUT, mark_used$OFFSET, fieldValue);
    }

    private static final AddressLayout release$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("release"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierReleaseCallback release
     * }
     */
    public static final AddressLayout release$layout() {
        return release$LAYOUT;
    }

    private static final long release$OFFSET = $LAYOUT.byteOffset(groupElement("release"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierReleaseCallback release
     * }
     */
    public static final long release$offset() {
        return release$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierReleaseCallback release
     * }
     */
    public static MemorySegment release(MemorySegment struct) {
        return struct.get(release$LAYOUT, release$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierReleaseCallback release
     * }
     */
    public static void release(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(release$LAYOUT, release$OFFSET, fieldValue);
    }

    private static final AddressLayout available_slots$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("available_slots"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierAvailableSlotsCallback available_slots
     * }
     */
    public static final AddressLayout available_slots$layout() {
        return available_slots$LAYOUT;
    }

    private static final long available_slots$OFFSET = $LAYOUT.byteOffset(groupElement("available_slots"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierAvailableSlotsCallback available_slots
     * }
     */
    public static final long available_slots$offset() {
        return available_slots$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierAvailableSlotsCallback available_slots
     * }
     */
    public static MemorySegment available_slots(MemorySegment struct) {
        return struct.get(available_slots$LAYOUT, available_slots$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierAvailableSlotsCallback available_slots
     * }
     */
    public static void available_slots(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(available_slots$LAYOUT, available_slots$OFFSET, fieldValue);
    }

    private static final AddressLayout free$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("free"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierFreeCallback free
     * }
     */
    public static final AddressLayout free$layout() {
        return free$LAYOUT;
    }

    private static final long free$OFFSET = $LAYOUT.byteOffset(groupElement("free"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierFreeCallback free
     * }
     */
    public static final long free$offset() {
        return free$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierFreeCallback free
     * }
     */
    public static MemorySegment free(MemorySegment struct) {
        return struct.get(free$LAYOUT, free$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreCustomSlotSupplierFreeCallback free
     * }
     */
    public static void free(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(free$LAYOUT, free$OFFSET, fieldValue);
    }

    private static final AddressLayout user_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("user_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static final AddressLayout user_data$layout() {
        return user_data$LAYOUT;
    }

    private static final long user_data$OFFSET = $LAYOUT.byteOffset(groupElement("user_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static final long user_data$offset() {
        return user_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static MemorySegment user_data(MemorySegment struct) {
        return struct.get(user_data$LAYOUT, user_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static void user_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(user_data$LAYOUT, user_data$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

