// Generated by jextract

package io.temporal.sdkbridge;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TemporalCoreConnectionOptions {
 *     struct TemporalCoreByteArrayRef target_url;
 *     struct TemporalCoreByteArrayRef client_name;
 *     struct TemporalCoreByteArrayRef client_version;
 *     TemporalCoreMetadataRef metadata;
 *     TemporalCoreMetadataRef binary_metadata;
 *     struct TemporalCoreByteArrayRef api_key;
 *     struct TemporalCoreByteArrayRef identity;
 *     const struct TemporalCoreClientTlsOptions *tls_options;
 *     const struct TemporalCoreClientRetryOptions *retry_options;
 *     const struct TemporalCoreClientKeepAliveOptions *keep_alive_options;
 *     const struct TemporalCoreClientHttpConnectProxyOptions *http_connect_proxy_options;
 *     TemporalCoreClientGrpcOverrideCallback grpc_override_callback;
 *     void *grpc_override_callback_user_data;
 * }
 * }
 */
public class TemporalCoreConnectionOptions {

    TemporalCoreConnectionOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TemporalCoreByteArrayRef.layout().withName("target_url"),
        TemporalCoreByteArrayRef.layout().withName("client_name"),
        TemporalCoreByteArrayRef.layout().withName("client_version"),
        TemporalCoreByteArrayRefArray.layout().withName("metadata"),
        TemporalCoreByteArrayRefArray.layout().withName("binary_metadata"),
        TemporalCoreByteArrayRef.layout().withName("api_key"),
        TemporalCoreByteArrayRef.layout().withName("identity"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("tls_options"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("retry_options"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("keep_alive_options"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("http_connect_proxy_options"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("grpc_override_callback"),
        temporal_sdk_core_c_bridge_h.C_POINTER.withName("grpc_override_callback_user_data")
    ).withName("TemporalCoreConnectionOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout target_url$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("target_url"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef target_url
     * }
     */
    public static final GroupLayout target_url$layout() {
        return target_url$LAYOUT;
    }

    private static final long target_url$OFFSET = $LAYOUT.byteOffset(groupElement("target_url"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef target_url
     * }
     */
    public static final long target_url$offset() {
        return target_url$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef target_url
     * }
     */
    public static MemorySegment target_url(MemorySegment struct) {
        return struct.asSlice(target_url$OFFSET, target_url$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef target_url
     * }
     */
    public static void target_url(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, target_url$OFFSET, target_url$LAYOUT.byteSize());
    }

    private static final GroupLayout client_name$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("client_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_name
     * }
     */
    public static final GroupLayout client_name$layout() {
        return client_name$LAYOUT;
    }

    private static final long client_name$OFFSET = $LAYOUT.byteOffset(groupElement("client_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_name
     * }
     */
    public static final long client_name$offset() {
        return client_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_name
     * }
     */
    public static MemorySegment client_name(MemorySegment struct) {
        return struct.asSlice(client_name$OFFSET, client_name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_name
     * }
     */
    public static void client_name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, client_name$OFFSET, client_name$LAYOUT.byteSize());
    }

    private static final GroupLayout client_version$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("client_version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_version
     * }
     */
    public static final GroupLayout client_version$layout() {
        return client_version$LAYOUT;
    }

    private static final long client_version$OFFSET = $LAYOUT.byteOffset(groupElement("client_version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_version
     * }
     */
    public static final long client_version$offset() {
        return client_version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_version
     * }
     */
    public static MemorySegment client_version(MemorySegment struct) {
        return struct.asSlice(client_version$OFFSET, client_version$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef client_version
     * }
     */
    public static void client_version(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, client_version$OFFSET, client_version$LAYOUT.byteSize());
    }

    private static final GroupLayout metadata$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("metadata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreMetadataRef metadata
     * }
     */
    public static final GroupLayout metadata$layout() {
        return metadata$LAYOUT;
    }

    private static final long metadata$OFFSET = $LAYOUT.byteOffset(groupElement("metadata"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreMetadataRef metadata
     * }
     */
    public static final long metadata$offset() {
        return metadata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreMetadataRef metadata
     * }
     */
    public static MemorySegment metadata(MemorySegment struct) {
        return struct.asSlice(metadata$OFFSET, metadata$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreMetadataRef metadata
     * }
     */
    public static void metadata(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, metadata$OFFSET, metadata$LAYOUT.byteSize());
    }

    private static final GroupLayout binary_metadata$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("binary_metadata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreMetadataRef binary_metadata
     * }
     */
    public static final GroupLayout binary_metadata$layout() {
        return binary_metadata$LAYOUT;
    }

    private static final long binary_metadata$OFFSET = $LAYOUT.byteOffset(groupElement("binary_metadata"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreMetadataRef binary_metadata
     * }
     */
    public static final long binary_metadata$offset() {
        return binary_metadata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreMetadataRef binary_metadata
     * }
     */
    public static MemorySegment binary_metadata(MemorySegment struct) {
        return struct.asSlice(binary_metadata$OFFSET, binary_metadata$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreMetadataRef binary_metadata
     * }
     */
    public static void binary_metadata(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, binary_metadata$OFFSET, binary_metadata$LAYOUT.byteSize());
    }

    private static final GroupLayout api_key$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("api_key"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef api_key
     * }
     */
    public static final GroupLayout api_key$layout() {
        return api_key$LAYOUT;
    }

    private static final long api_key$OFFSET = $LAYOUT.byteOffset(groupElement("api_key"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef api_key
     * }
     */
    public static final long api_key$offset() {
        return api_key$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef api_key
     * }
     */
    public static MemorySegment api_key(MemorySegment struct) {
        return struct.asSlice(api_key$OFFSET, api_key$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef api_key
     * }
     */
    public static void api_key(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, api_key$OFFSET, api_key$LAYOUT.byteSize());
    }

    private static final GroupLayout identity$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("identity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef identity
     * }
     */
    public static final GroupLayout identity$layout() {
        return identity$LAYOUT;
    }

    private static final long identity$OFFSET = $LAYOUT.byteOffset(groupElement("identity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef identity
     * }
     */
    public static final long identity$offset() {
        return identity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef identity
     * }
     */
    public static MemorySegment identity(MemorySegment struct) {
        return struct.asSlice(identity$OFFSET, identity$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TemporalCoreByteArrayRef identity
     * }
     */
    public static void identity(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, identity$OFFSET, identity$LAYOUT.byteSize());
    }

    private static final AddressLayout tls_options$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("tls_options"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientTlsOptions *tls_options
     * }
     */
    public static final AddressLayout tls_options$layout() {
        return tls_options$LAYOUT;
    }

    private static final long tls_options$OFFSET = $LAYOUT.byteOffset(groupElement("tls_options"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientTlsOptions *tls_options
     * }
     */
    public static final long tls_options$offset() {
        return tls_options$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientTlsOptions *tls_options
     * }
     */
    public static MemorySegment tls_options(MemorySegment struct) {
        return struct.get(tls_options$LAYOUT, tls_options$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientTlsOptions *tls_options
     * }
     */
    public static void tls_options(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(tls_options$LAYOUT, tls_options$OFFSET, fieldValue);
    }

    private static final AddressLayout retry_options$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("retry_options"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientRetryOptions *retry_options
     * }
     */
    public static final AddressLayout retry_options$layout() {
        return retry_options$LAYOUT;
    }

    private static final long retry_options$OFFSET = $LAYOUT.byteOffset(groupElement("retry_options"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientRetryOptions *retry_options
     * }
     */
    public static final long retry_options$offset() {
        return retry_options$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientRetryOptions *retry_options
     * }
     */
    public static MemorySegment retry_options(MemorySegment struct) {
        return struct.get(retry_options$LAYOUT, retry_options$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientRetryOptions *retry_options
     * }
     */
    public static void retry_options(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(retry_options$LAYOUT, retry_options$OFFSET, fieldValue);
    }

    private static final AddressLayout keep_alive_options$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("keep_alive_options"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientKeepAliveOptions *keep_alive_options
     * }
     */
    public static final AddressLayout keep_alive_options$layout() {
        return keep_alive_options$LAYOUT;
    }

    private static final long keep_alive_options$OFFSET = $LAYOUT.byteOffset(groupElement("keep_alive_options"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientKeepAliveOptions *keep_alive_options
     * }
     */
    public static final long keep_alive_options$offset() {
        return keep_alive_options$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientKeepAliveOptions *keep_alive_options
     * }
     */
    public static MemorySegment keep_alive_options(MemorySegment struct) {
        return struct.get(keep_alive_options$LAYOUT, keep_alive_options$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientKeepAliveOptions *keep_alive_options
     * }
     */
    public static void keep_alive_options(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(keep_alive_options$LAYOUT, keep_alive_options$OFFSET, fieldValue);
    }

    private static final AddressLayout http_connect_proxy_options$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("http_connect_proxy_options"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientHttpConnectProxyOptions *http_connect_proxy_options
     * }
     */
    public static final AddressLayout http_connect_proxy_options$layout() {
        return http_connect_proxy_options$LAYOUT;
    }

    private static final long http_connect_proxy_options$OFFSET = $LAYOUT.byteOffset(groupElement("http_connect_proxy_options"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientHttpConnectProxyOptions *http_connect_proxy_options
     * }
     */
    public static final long http_connect_proxy_options$offset() {
        return http_connect_proxy_options$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientHttpConnectProxyOptions *http_connect_proxy_options
     * }
     */
    public static MemorySegment http_connect_proxy_options(MemorySegment struct) {
        return struct.get(http_connect_proxy_options$LAYOUT, http_connect_proxy_options$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TemporalCoreClientHttpConnectProxyOptions *http_connect_proxy_options
     * }
     */
    public static void http_connect_proxy_options(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(http_connect_proxy_options$LAYOUT, http_connect_proxy_options$OFFSET, fieldValue);
    }

    private static final AddressLayout grpc_override_callback$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("grpc_override_callback"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporalCoreClientGrpcOverrideCallback grpc_override_callback
     * }
     */
    public static final AddressLayout grpc_override_callback$layout() {
        return grpc_override_callback$LAYOUT;
    }

    private static final long grpc_override_callback$OFFSET = $LAYOUT.byteOffset(groupElement("grpc_override_callback"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporalCoreClientGrpcOverrideCallback grpc_override_callback
     * }
     */
    public static final long grpc_override_callback$offset() {
        return grpc_override_callback$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporalCoreClientGrpcOverrideCallback grpc_override_callback
     * }
     */
    public static MemorySegment grpc_override_callback(MemorySegment struct) {
        return struct.get(grpc_override_callback$LAYOUT, grpc_override_callback$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporalCoreClientGrpcOverrideCallback grpc_override_callback
     * }
     */
    public static void grpc_override_callback(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(grpc_override_callback$LAYOUT, grpc_override_callback$OFFSET, fieldValue);
    }

    private static final AddressLayout grpc_override_callback_user_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("grpc_override_callback_user_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *grpc_override_callback_user_data
     * }
     */
    public static final AddressLayout grpc_override_callback_user_data$layout() {
        return grpc_override_callback_user_data$LAYOUT;
    }

    private static final long grpc_override_callback_user_data$OFFSET = $LAYOUT.byteOffset(groupElement("grpc_override_callback_user_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *grpc_override_callback_user_data
     * }
     */
    public static final long grpc_override_callback_user_data$offset() {
        return grpc_override_callback_user_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *grpc_override_callback_user_data
     * }
     */
    public static MemorySegment grpc_override_callback_user_data(MemorySegment struct) {
        return struct.get(grpc_override_callback_user_data$LAYOUT, grpc_override_callback_user_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *grpc_override_callback_user_data
     * }
     */
    public static void grpc_override_callback_user_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(grpc_override_callback_user_data$LAYOUT, grpc_override_callback_user_data$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

